### ISSUE TITLE
envi requirement missing

### ISSUE THREAD

**Issue by noraj** [williballenthin/viv-utils#121]
[envi](https://pypi.org/project/envi/) is required in several files

https://github.com/williballenthin/viv-utils/blob/8f848c55f7498f717f5569899888212367636eb7/viv_utils/__init__.py#L9
https://github.com/williballenthin/viv-utils/blob/8f848c55f7498f717f5569899888212367636eb7/viv_utils/flirt.py#L7

but is not required in https://github.com/williballenthin/viv-utils/blob/8f848c55f7498f717f5569899888212367636eb7/setup.py#L7-L12

which leads to the following error in flare-floss that is requiring viv-utils

```
Traceback (most recent call last):
  File "/usr/bin/floss", line 33, in <module>
    sys.exit(load_entry_point('flare-floss==2.3.0', 'console_scripts', 'floss')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/floss", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/floss/main.py", line 17, in <module>
    import viv_utils
  File "/usr/lib/python3.11/site-packages/viv_utils/__init__.py", line 9, in <module>
    import envi
ModuleNotFoundError: No module named 'envi'
```

https://github.com/mandiant/flare-floss/blob/e0a040c0f30466997763886037f2c739d3008d63/floss/main.py#L17

**Comment by williballenthin** [comment]
`envi` comes from the vivisect package: https://github.com/vivisect/vivisect/tree/master/envi

so, would you confirm that you have vivisect installed?
